name: week_1_assignment
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  equatable: ^2.0.7
  flutter_bloc: ^8.1.3
  dio: ^5.8.0+1
  retrofit: ^4.6.0
  json_annotation: ^4.9.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  retrofit_generator: ^10.0.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile_pic.jpg
